version: '3.9'

services:

  mysql-kc:
    image: mysql:8.0.31
    ports:
      - 3366:3306
    restart: unless-stopped
    environment:
      # The user, password and database that Keycloak
      # is going to create and use
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
      # Self-Explanatory
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8181:8080
    restart: unless-stopped
    environment:
      # User and password for the Administration Console
      KEYCLOAK_ADMIN: admin_user
      KEYCLOAK_ADMIN_PASSWORD: admin_password 
      KEYCLOAK_USER: admin_user
      KEYCLOAK_PASSWORD: admin_password
      DB_VENDOR: mysql
      DB_ADDR: mysql-kc
      DB_PORT: 3306
      # Same values as the mysql-kc service
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      DB_DATABASE: keycloak_db
    depends_on:
      - mysql-kc
    command: start-dev
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: